apiVersion: v1
kind: Service
metadata:
  name: go-lang
  labels:
    app: go-lang
spec:
  selector:
    app: go-lang
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


