apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-lang
  labels:
    app: go-lang
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-lang
  template:
    metadata:
      labels:
        app: go-lang
    spec:
      containers:
      - name: go-lang
        image: kamalsai33/go-web-app:v2
        ports:
        - containerPort: 8080
