name: action
#run action
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Build
        run: go build -o go-web-app
      
      - name: Test
        run: go test ./...

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.2

  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: setup docker build
        uses: docker/setup-buildx-action@v2

      - name: login to DockerHub
        uses: docker/log-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}

    update-newtag-in-helm:
      runs-on: ubuntu-latest

      needs: push

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.TOKEN }}

        - name: Update tag in Helm chart
          run: |
            sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml

        - name: Commit and push changes
          run: |
            git config --global user.email "kamaleshsai33@gmail.com"
            git config --global user.name "Sai Kamalesh"
            git add helm/go-web-app-chart/values.yaml
            git commit -m "Update tag in Helm chart"
            git push
